# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'лікар',
                'verbose_name_plural': 'лікарі',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2017, 6, 29), verbose_name='дата вимірювання')),
                ('time', models.TimeField(default=datetime.time(14, 20, 9, 247563), verbose_name='час вимірювання')),
                ('upper', models.PositiveSmallIntegerField(help_text='Верхній тиск', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='верхній')),
                ('lower', models.PositiveSmallIntegerField(help_text='Нижній тиск', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='нижній')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, help_text='Частота пульсу', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='пульс')),
                ('doctor', models.ForeignKey(help_text='Виберіть лікарів, або значення "Я сам"', on_delete=django.db.models.deletion.CASCADE, to='tysk.Doctor', verbose_name='лікар')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва, кількість, дозування...')),
            ],
            options={
                'verbose_name': 'ліки',
                'verbose_name_plural': 'ліки',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField(default=True, verbose_name='стать')),
                ('doctors', models.ManyToManyField(to='tysk.Doctor', verbose_name='лікар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'пацієнт',
                'verbose_name_plural': 'пацієнти',
            },
        ),
        migrations.AddField(
            model_name='main',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tysk.Medicament', verbose_name='ліки'),
        ),
        migrations.AddField(
            model_name='main',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tysk.Patient', verbose_name='пацієнт'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='tysk.Patient', verbose_name='паціент'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
    ]
