# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tysk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='time',
            field=models.TimeField(default=datetime.time(14, 21, 45, 881288), verbose_name='час вимірювання'),
        ),
    ]
