# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tysk.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tysk', '0002_auto_20170629_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='owner',
            field=models.ForeignKey(default=tysk.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='власник'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='owner',
            field=models.ForeignKey(default=tysk.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='власник'),
        ),
        migrations.AlterField(
            model_name='main',
            name='date',
            field=models.DateField(default=datetime.date(2017, 7, 10), verbose_name='дата вимірювання'),
        ),
        migrations.AlterField(
            model_name='main',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tysk.Doctor', verbose_name='лікар'),
        ),
        migrations.AlterField(
            model_name='main',
            name='lower',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='нижній'),
        ),
        migrations.AlterField(
            model_name='main',
            name='pulse',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='пульс'),
        ),
        migrations.AlterField(
            model_name='main',
            name='time',
            field=models.TimeField(default=datetime.time(11, 13, 45, 273043), verbose_name='час вимірювання'),
        ),
        migrations.AlterField(
            model_name='main',
            name='upper',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='верхній'),
        ),
    ]
