# Generated by Django 2.1.5 on 2019-06-21 11:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tysk', '0005_auto_20170811_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'головна', 'verbose_name_plural': 'головні'},
        ),
        migrations.AlterField(
            model_name='main',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 21), verbose_name='дата вимірювання'),
        ),
        migrations.AlterField(
            model_name='main',
            name='time',
            field=models.TimeField(default=datetime.time(14, 58, 48, 816145), verbose_name='час вимірювання'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
    ]
