from django.conf.urls import url
from tysk import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^doctors/$', views.DoctorsList.as_view(), name='doctors-list'),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^doctors/add/$', views.DoctorCreate.as_view(), name='doctor-add'),
    url(r'^doctors/(?P<pk>[0-9]+)/update/$', views.DoctorUpdate.as_view(), name='doctor-update'),
    url(r'^doctors/(?P<pk>[0-9]+)/confirm/$', views.DoctorDelete.as_view(), name='doctor-delete'),
    url(r'^mains/$', views.MainsList.as_view(), name='mains-list'),
    url(r'^mains/(?P<pk>[0-9]+)/$', views.MainDetail.as_view(), name='main-detail'),
    url(r'^mains/add/$', views.MainCreate.as_view(), name='main-add'),
    url(r'^mains/(?P<pk>[0-9]+)/update/$', views.MainUpdate.as_view(), name='main-update'),
    url(r'^mains/(?P<pk>[0-9]+)/confirm/$', views.MainDelete.as_view(), name='main-delete'),
    url(r'^medicaments/$', views.MedicamentsList.as_view(), name='medicaments-list'),
    url(r'^medicaments/(?P<pk>[0-9]+)/$', views.MedicamentDetail.as_view(), name='medicament-detail'),
    url(r'^medicaments/add/$', views.MedicamentCreate.as_view(), name='medicament-add'),
    url(r'^medicaments/(?P<pk>[0-9]+)/update/$', views.MedicamentUpdate.as_view(), name='medicament-update'),
    url(r'^medicaments/(?P<pk>[0-9]+)/confirm/$', views.MedicamentDelete.as_view(), name='medicament-delete'),
    url(r'^users/login/$', views.login, name='login'),
    url(r'^users/reg/$', views.register, name='register'),
    url(r'^users/forget/$', views.forget_password, name='forget-password'),
    url(r'^users/$', views.UsersList.as_view(), name='users-list'),
    # url(r'^users/create/$', views.UserCreate.as_view(), name='user-create'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^users/(?P<pk>[0-9]+)/update/$', views.UserUpdate.as_view(), name='user-update'),
    url(r'^users/(?P<pk>[0-9]+)/confirm/$', views.UserDelete.as_view(), name='user-delete'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass/$', views.UserChangePass.as_view(), name='user-change-password'),
    url(r'^users/(?P<pk>[0-9]+)/change/pass_old/$', views.UserChangePassOld.as_view(), name='user-change-pass-old'),
    url(r'^users/(?P<pk>[0-9]+)/reset/pass/$', views.UserResetPass.as_view(), name='user-reset-password'),
    url(r'^users/logout/$', views.logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^patients/$', views.PatientsList.as_view(), name='patients-list'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetail.as_view(), name='patient-detail'),
    url(r'^patients/add/$', views.PatientCreate.as_view(), name='patient-add'),
    url(r'^patients/(?P<pk>[0-9]+)/update/$', views.PatientUpdate.as_view(), name='patient-update'),
    url(r'^patients/(?P<pk>[0-9]+)/confirm/$', views.PatientDelete.as_view(), name='patient-delete'),
    url(r'^code/$', views.code, name='code')
]